version: '3'
services:
  rabbit:
     container_name: starter_rabbit
     hostname: rabbit
     image: rabbitmq:3.6.6-management
     environment:
        - RABBITMQ_DEFAULT_USER = user
        - RABBITMQ_DEFAULT_PASS = pass
     ports:
        - "5672:5672"
        - "15672:15672"